### ISSUE TITLE
Please help me to fix the failing tasks

### ISSUE THREAD

**Issue by alexandercoabad** [TinyTapeout/tt05-submission-template#3]
here is my wokwi circuit https://wokwi.com/projects/392841802340521985

thanks,
alex

**Comment by urish** [comment]
Hi Alex, 

Please use the [discord chat](https://tinytapeout.com/discord) for questions, you'll get faster replies there.

The issue with the Wokwi circuit is that it's using an outdated template, that is no longer supported since Tiny Tapeout 3.

You can find the up to date template here (and copy-paste your design into that template):

https://wokwi.com/projects/354858054593504257

Or, if you want to manually upgrade your project, there are instructions here: [Upgrading from Tiny Tapeout 2 to Tiny Tapeout 4+](https://docs.google.com/document/d/11rM7nueEaFlofURAL9AmQxe8ajUYbQg5K83TQFf4LhY/edit#heading=h.xq9tm2916wz4)
